version: '3'

services:
  client-app: 
    build:
      context: ./health-clinic
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Corrected 'port' to 'ports'
    env_file:  # Use 'env_file' to specify environment variables
      - ./health-clinic/.env

  admin-app: 
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "3002:3000"  # Corrected 'port' to 'ports'
    env_file:  # Use 'env_file' to specify environment variables
      - ./admin-panel/.env
